GrandeTravelMVC/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GrandeTravelMVC.Models
{
    public class Order
    {
        public int OrderId { get; set; }
        public double TotalPrice { get; set; }
        public DateTime Date { get; set; }
        public int Quantity { get; set; }
        public string PackageName { get; set; }
        public int PackageId { get; set; }
        public string UserId { get; set; }
    }
}

GrandeTravelMVC/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravelMVC.Models;
using GrandeTravelMVC.Services;
using GrandeTravelMVC.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravelMVC.Controllers
{
    public class FeedbackController : Controller
    {
        private UserManager<IdentityUser> _userManagerService;
        private IDataService<Package> _packageDataService;
        private IDataService<Feedback> _feedbackDataService;

        public FeedbackController(UserManager<IdentityUser> userManager,
                                 IDataService<Package> packageService,
                                 IDataService<Feedback> feedbackService)
        {
            _userManagerService = userManager;
            _packageDataService = packageService;
            _feedbackDataService = feedbackService;
        }


        [HttpGet]
        [Authorize(Roles = "Customer")]
        public IActionResult Create(int id)
        {
            Package package = _packageDataService.GetSingle(p => p.PackageId == id);

            FeedbackCreateViewModel vm = new FeedbackCreateViewModel
            {
                PackageId = package.PackageId,
                Name = package.Name,
                Location = package.Location,
                Description = package.Description
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Create(FeedbackCreateViewModel vm)
        {
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);

            Feedback feedback = new Feedback
            {
                Rating = vm.Rating,
                Description = vm.FDescription,
                PackageId = vm.PackageId,
                UserId = user.Id
            };
            _feedbackDataService.Create(feedback);

            return RedirectToAction("Index", "Home");

            //return RedirectToAction("Details","Package", new { id = vm.PackageId});
        }
    }
}

GrandeTravelMVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravelMVC.Models;
using GrandeTravelMVC.Services;
using GrandeTravelMVC.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace GrandeTravelMVC.Controllers
{
    public class OrderController : Controller
    {
        private UserManager<IdentityUser> _userManagerService;
        private IDataService<Order> _orderDataService;
        private IDataService<Package> _packageDataService;

        public OrderController(UserManager<IdentityUser> userManager,
                                 IDataService<Package> packageService,
                                 IDataService<Order> orderService)
        {
            _userManagerService = userManager;
            _packageDataService = packageService;
            _orderDataService = orderService;
        }

        [HttpGet]
        [Authorize(Roles = "Customer")]
        public IActionResult Create()
        {
            int packageId = int.Parse(TempData["packageId"].ToString());

            Package package = _packageDataService.GetSingle(p => p.PackageId == packageId);

            OrderCreateViewModel vm = new OrderCreateViewModel
            {
                PackageId = package.PackageId,
                Name = package.Name,
                Quantity = 1,
                Location = package.Location,
                Price = package.Price,
                Description = package.Description,
                Picture = package.Picture
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Create(OrderCreateViewModel vm)
        {
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);

            if (ModelState.IsValid)
            {
                Order order = new Order
                {
                    Date = DateTime.Now,
                    PackageName = vm.Name,
                    PackageId = vm.PackageId,
                    Quantity = vm.Quantity,
                    TotalPrice = vm.Quantity * vm.Price,
                    UserId = user.Id
                };
                _orderDataService.Create(order);

                //send email
                //var apiKey = ("xxxxxxx");
                //var client = new SendGridClient(apiKey);
                //var from = new EmailAddress("someone1@email.com", "Jane Smith");
                //var subject = "Order confirmation: Grande Travel";
                //var to = new EmailAddress("someone2@email.com", "John Brown");
                //var plainTextContent = "Thanks for booking with us!";
                //var htmlContent = "<strong>Safe travels</strong>";
                //var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
                //var bytes = System.IO.File.ReadAllBytes("GrandeTravelMVC/wwwroot/attachments/voucher.txt");
                //var file = Convert.ToBase64String(bytes);
                //msg.AddAttachment("voucher.txt", file);
                //var response = await client.SendEmailAsync(msg);

                return RedirectToAction("Details", "Order", new { id = order.OrderId });
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Customer")]
        public IActionResult Details(int id)
        {
            Order order = _orderDataService.GetSingle(o => o.OrderId == id);

            OrderDetailsViewModel vm = new OrderDetailsViewModel
            {
                OrderId = order.OrderId,
                PackageName = order.PackageName,
                Quantity = order.Quantity,
                TotalPrice = order.TotalPrice,
                Date = order.Date,
            };

            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> DetailsPast()
        {
            IdentityUser user = await _userManagerService.FindByNameAsync(User.Identity.Name);

            IEnumerable<Order> orderList = _orderDataService.Query(o => o.UserId == user.Id);

            OrderDetailsPastViewModel vm = new OrderDetailsPastViewModel
            {
                Orders = orderList,
                Count = orderList.Count()
            };

            return View(vm);
        }
    }
}

GrandeTravelMVC/Views/Order/Create.cshtml
@model OrderCreateViewModel

<div class="bg-light pb-5">

    <div class="container">
        <div class="py-5 text-center">
            <h2>Order package</h2>
            <p class="lead">Please fill in the form and review details</p>
        </div>

        <div class="row mx-auto" style="width:80%">
            <div class="col-md-6 order-md-1">
                <h4 class="mb-3">Order details</h4>
                <form asp-controller="Order" asp-action="Create" asp-antiforgery="true" method="Post" enctype="multipart/form-data">

                    <div asp-validation-summary="ModelOnly">

                    </div>

                    <div>
                        <input hidden="hidden" asp-for="PackageId" />
                    </div>

                    <div>
                        <input hidden="hidden" asp-for="Name" />
                    </div>

                    <div class="mb-3">
                        <label asp-for="Price">Price Per Person</label>
                        <input type="text" class="form-control" asp-for="Price" readonly>
                        <span style="color:red" asp-validation-for="Price"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Name">Package Name</label>
                        <input type="text" class="form-control" asp-for="Name" readonly>
                        <span style="color:red" asp-validation-for="Name"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Quantity"></label>
                        <input type="text" class="form-control" asp-for="Quantity">
                        <span style="color:red" asp-validation-for="Quantity"></span>
                    </div>

                    <hr class="mb-4">

                    <button class="btn btn-primary" style="background-color:darkcyan; border-color:darkcyan" type="submit">Order</button>
                </form>
            </div>
            <div class="col-md-6 order-md-1">
                <div class="mx-auto mt-4">
                    <img src="~/uploads/package/@Model.Picture" alt="Package Picture" style="width:100%" /> @*style="width:600px*@
                </div>
                <div>
                    <p class="font-weight-bold">Location</p>
                    <p>@Model.Location</p>
                </div>
                <div>
                    <p class="font-weight-bold">Description</p>
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>

    </div>

</div>

GrandeTravelMVC/Views/Order/Details.cshtml
@model OrderDetailsViewModel

<div class="bg-light pb-5">

    <div class="container">
        <div class="py-5 text-center">
            <h2>Confirm order and pay</h2>
            <p class="lead">Please confirm and pay</p>
        </div>

        <div class="row mx-auto" style="width:80%">
            <div class="col-md-6 order-md-1">
                <h4 class="mb-3">Order details</h4>
                <div class="mb-2">
                    <span class="font-weight-bold">Order Id</span>
                    <span>@Model.OrderId</span>
                </div>
                <div class="mb-2">
                    <span class="font-weight-bold">Package Name</span>
                    <span>@Model.PackageName</span>
                </div>
                <div class="mb-2">
                    <span class="font-weight-bold">Quantity</span>
                    <span>@Model.Quantity</span>
                </div>
                <div class="mb-2">
                    <span class="font-weight-bold">Total Price</span>
                    <span>$ @Model.TotalPrice</span>
                </div>
                <div class="mb-2">
                    <span class="font-weight-bold">Date</span>
                    <span>@Model.Date</span>
                </div>
            </div>
            <div class="col-md-6 order-md-1">
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="K6TNES3J4B7MS">
                    <input type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
                    <img alt="" border="0" src="https://www.paypalobjects.com/en_AU/i/scr/pixel.gif" width="1" height="1">
                </form>
            </div>
        </div>

    </div>

</div>

GrandeTravelMVC/Views/Order/DetailsPast.cshtml
@model OrderDetailsPastViewModel

<div class="container" style="min-height:525px">
    <div class="row">
        <div class="col-md-12 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3 pt-5">
                <span class="text-muted">Your orders</span>
                <span class="badge badge-secondary badge-pill">@Model.Count</span>
            </h4>
            <table class="table table-light">
                <tr>
                    <th scope="col">Order Id</th>
                    <th scope="col">Package Name</th>
                    <th scope="col">Date</th>
                    <th scope="col"></th>
                </tr>
                @foreach (var item in Model.Orders)
                {

                    <tr>
                        <td>@item.OrderId</td>
                        <td>@item.PackageName</td>
                        <td>@item.Date.ToShortDateString()</td>
                        <td><a class="btn btn-primary" href="@Url.Action("Create","Feedback", new { id = item.PackageId})">Leave feedback</a></td>
                    </tr>
                }
            </table>
            @if (Model.Orders.Count() == 0)
            {
                <p>You have not made any orders yet</p>
            }
        </div>
    </div>
</div>