GrandeTravelMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravelMVC.Models;
using GrandeTravelMVC.Services;
using GrandeTravelMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace GrandeTravelMVC.Controllers
{
    public class HomeController : Controller
    {
        private IDataService<Location> _locationDataService;
        private IDataService<Package> _packageDataService;
        public HomeController(IDataService<Location> locationService,
                              IDataService<Package> packageService)
        {
            _locationDataService = locationService;
            _packageDataService = packageService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Location> locationList = _locationDataService.GetAll();
            IEnumerable<Package> packageList = _packageDataService.GetAll().Where(p => p.IsAvailable == true);

            HomeIndexViewModel vm = new HomeIndexViewModel
            {
                Locations = locationList,
                Packages = packageList,
            };
            return View(vm);
        }

        [HttpGet]
        public IActionResult About()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Help()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Terms()
        {
            return View();
        }
    }
}

GrandeTravelMVC/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeTravelMVC.Models;
using GrandeTravelMVC.Services;
using GrandeTravelMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GrandeTravelMVC.Controllers
{
    public class LocationController : Controller
    {
        private IDataService<Location> _locationDataService;
        private IDataService<Package> _packageDataService;

        public LocationController(IDataService<Package> packageService,
                                 IDataService<Location> locationService)
        {
            _packageDataService = packageService;
            _locationDataService = locationService;
        }

        [HttpGet]
        public IActionResult Details(int id, string name)
        {
            TempData["locationId"] = id.ToString();

            //Package package = _packageDataService.GetSingle(p => p.PackageId == id);

            //TempData["locationName"] = name;

            Location location = _locationDataService.GetSingle(p => p.LocationId == id);
            IEnumerable<Package> packageList = _packageDataService.Query(p => p.LocationId == id && p.IsAvailable == true);

            LocationDetailsViewModel vm = new LocationDetailsViewModel
            {
                Name = location.Name,
                Description = location.Description,
                Picture = location.Picture,
                Packages = packageList
            };

            return View(vm);
        }
    }
}

GrandeTravelMVC/Views/Home/About.cshtml
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h1 class="mb-5">About Us</h1>
            <h6>Company Background</h6>
            <p>
                Grande Travel is a network of the best luxury travel agencies, with more than 17,500 advisors worldwide. We represent the best of the best in travel, with a portfolio of nearly 1,700 preferred partners - top hotels, cruise lines, tour operators, and more. Our advisors use their global connections to plan the most memorable experiences for their clients, from weekend getaways to dream vacations.
            </p>
            <br />
            <h6>Company Goals</h6>
            <p>
                We aim to provide you with luxurious and exlusive travel experiences that can be found nowhere else.
                We aim to give you memories for years to come for your getaway whether it be for a family trip, 
                honeymoon, birthday, anniversary or other special occasion.
                We aim to provide packages that are value for money
            </p>
        </div>
    </div>
</div>

GrandeTravelMVC/Views/Home/Help.cshtml
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h1 class="mb-5">Help</h1>
            <h6>Contact Us</h6>
            <p>
                For Travelers

                Our staff is available to help you 8 a.m. to 7 p.m AEST Monday through Friday.

                For help connecting with a travel provider:
                Find a travel provider
                Call +1-817-870-0300
                Email: help@grandetravel.com

                For help with grandetravel.com:
                Call +1-817-870-0300
                Email: help@grandetravel.com
            </p>
            <p>
                For Travel Professionals

                Agency owners or managers interested in more information about membership, please contact us.
                Consultants, agents, or anyone searching for a career in travel can learn more about becoming a travel provider
                Travel providers, including hotels, tour companies, cruise lines, etc., who are interested in becoming Grande Travel preferred suppliers, please email us at help@grandetravel.com or call +1-817-870-0300.
            </p>
        </div>
    </div>
</div>

GrandeTravelMVC/Views/Home/Index.cshtml
@model HomeIndexViewModel

<header class="row">
    <div class="col">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="2500">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-caption d-none d-md-block text-left" style="bottom:600px">
                            <h1 class="display-4" style="color:white">Explore Australia your own way with exclusive luxury packages</h1>
                            <br />
                            <p><a class="btn btn-primary btn-lg" style="background-color:blue; border-color:blue" href="#home-first-section" role="button">Browse Destinations</a></p>
                        </div>
                        <img class="d-block w-100 mx-auto" src="~/images/australiabeachbikini785066.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption d-none d-md-block text-left" style="bottom:600px">
                            <h1 class="display-4" style="color:white">Explore Australia your own way with exclusive luxury packages</h1>
                            <br />
                            <p><a class="btn btn-primary btn-lg" style="background-color:blue; border-color:blue" href="#home-first-section" role="button">Browse Destinations</a></p>
                        </div>
                        <img class="d-block w-100 mx-auto" src="~/images/australiabeachbondibeach785133.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-caption d-none d-md-block text-left" style="bottom:600px">
                            <h1 class="display-4" style="color:white">Explore Australia your own way with exclusive luxury packages</h1>
                            <br />
                            <p><a class="btn btn-primary btn-lg" style="background-color:blue; border-color:blue" href="#home-first-section" role="button">Browse Destinations</a></p>
                        </div>
                        <img class="d-block w-100 mx-auto" src="~/images/beachbondibeachcoast785065.jpg" alt="Third slide">
                    </div>
                </div>
            </div>
    </div>
</header>

<div class="container-fluid" id="home-first-section">

    <br />
    <br />
    <h5>Escapes by City</h5>

    <div class="card-deck row m-5">

        @foreach (var item in Model.Locations)
        {
            <div class="card" style="max-width: 18rem;">
                <a href="@Url.Action("Details", "Location", new { id = item.LocationId })">
                    <img class="card-img-top" src="~/uploads/location/@item.Picture" alt="location photo">
                    <div class="card-img-overlay">

                    </div>
                </a>
                <div class="card-footer text-center bg-dark">
                    <p class="card-title text-light font-weight-bold">@item.Name</p>
                </div>
            </div>
        }

    </div>

    @foreach (var item in Model.Locations)
    {
        <h5>Featured @item.Name Escapes</h5>
        <div class="card-deck row m-5">

            @foreach (var package in Model.Packages.Where(p => p.Location == item.Name && p.IsAvailable == true).Take(4))
            {
                <div class="card" style="max-width: 18rem;">
                    <a href="@Url.Action("Details", "Package", new { id = package.PackageId})">
                        <img class="card-img-top" src="~/uploads/package/@package.Picture" alt="location photo">
                        <div class="card-img-overlay">

                        </div>
                    </a>
                    <div class="card-footer text-center bg-dark">
                        <p class="card-title text-light font-weight-bold">@package.Name</p>
                    </div>
                </div>
            }
        </div>
    }

    <!--The div element for the map -->
    <div id="map"></div>
    <script>
        // Initialize and add the map
        function initMap() {
            // The location
            var sydney1 = { lat: -33.861, lng: 151.211 };
            // The map, centered at location
            var map = new google.maps.Map(
                document.getElementById('map'), { zoom: 4, center: sydney1 });
            // The marker, positioned at location
            var marker = new google.maps.Marker({ position: sydney1, map: map });
        }
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAog8xV_3I3tPfMnjTI7XSu1Sa-KkSouPc&callback=initMap">
    </script>

</div>

GrandeTravelMVC/Views/Home/Terms.cshtml
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h1 class="mb-5">Terms and Conditions</h1>
            <h6>The legal stuff</h6>
            <p>
                1. YOUR USE OF THIS SITE
                These terms and conditions apply to your use of this internet site. By using this Site you agree to be bound by these terms and conditions.

                2. DEFINITIONS
                On this Site:

                • "Content" of this Site includes things that you may see, read, hear, download or access on or via the Site (including but not limited to messages, files, data, software, images, photographs, illustrations, text and other materials).
                • "Principal" means a service provider who provides travel services offered through this site and on whose behalf we act as booking agent.
                • "Site" means this internet site www.traveltheworld.com.au and its sub-domains, forms.grandetravel.com.au and reservations.grandetravel.com.au.
                • "Grande Travel", "we" or "us" means Grande Travel (TTW) Pty Ltd trading as Grande Travel. Grande Travel holds Travel Agents Licence 2TA 003774, is a member of the Travel Compensation Fund and is a member of the Australian Federation of Travel Agents.

                3. OTHER TERMS AND CONDITIONS MAY APPLY
                Your use of some parts or features of the Site may be governed by additional terms and conditions, dictated by each Principal represented by Grande Travel from time to time. In particular, each Principal has their own booking terms and conditions that will apply when making a booking through this Site. Those additional terms and conditions:

                (a) apply to your use of such parts of the Site or features in addition to these terms and conditions; and

                (b) prevail over these terms and conditions to the extent of any inconsistency.

                4. INTELLECTUAL PROPERTY RIGHTS
                The Content on the Site is subject to copyright and possibly other intellectual property rights.
                Unless you are expressly authorised by law you must not or permit any other person, to:

                (a) sell, reproduce, distribute, modify, display, publicly perform, prepare derivative works based on, repost or otherwise use any of the Content in any way for any public or commercial purpose without our prior written consent; or

                (b) otherwise infringe the intellectual property rights of any person in using the Site or any Content.
                Nothing you do on or in relation to the Site will transfer any intellectual property rights in the Content to you or licence you to exercise any intellectual property rights in the Content.

                Our corporate logo “Grande Travel” is our trademark. All rights are reserved by us. All trademarks (whether registered or unregistered) and logos appearing on our Site must not be used without obtaining the prior written consent of their owner.

                5. CONTENT OF THE SITE
                We attempt to keep the Content of the Site up to date. However, most of the Content is supplied to us by third party providers. Although we take reasonable steps to confirm its accuracy and currency, we do not warrant the accuracy or currency of the Content.

                The Content on the Site is liable to change at any time without notice.

                Prices quoted on the Site are in various currencies depending on the Principal. Please ensure that you confirm the price and the relevant currency before making your booking.

                Prices quoted on the Site should be used as a guide only and are not guaranteed, as they may change from time to time according to each respective Principal.
                Any travel services advertised on this Site including prices are subject to availability.

                6. YOUR USE OF THE SITE
                In using this Site you must not:

                (a) disrupt or interfere with the Site or servers or other software, hardware or equipment connected to or via the Site;

                (b) reproduce any Content from our Site without our express written permission, which we may withhold or grant in our absolute discretion;

                (c) interfere with other users use and enjoyment of the Site;

                (d) collect or store personal data about other users of the Site;

                (e) use another person's personal information without their permission;

                (f) make any fraudulent, speculative or false enquiries, bookings, reservations or requests;

                (g) post or transmit to or via the Site any unlawful, threatening, defamatory, libellous, obscene, indecent or pornographic material or any material that could give rise to civil or criminal proceedings;

                (h) knowingly transmit any virus or other disabling feature to the Site.

                7. PRIVACY
                Any personal information we collect from you will be handled in accordance with our Privacy Policy.

                8. LINKS, DOWNLOADS, PLUG-INS, FEATURES AND ADVERTISEMENTS
                We have not reviewed all of the sites, downloads, plug-ins, features or advertisements linked to this Site and are not responsible for the content or accuracy of any off-site pages or any other sites linked to this Site (including without limitation sites linked through advertisements or through any search engines).

                The inclusion of any link does not imply that we endorse the linked site, and you use the links at your own risk. We do not accept any responsibility or liability for any claims arising out of your use of these links or of the descriptions or information supplied to us by third parties for inclusion on this Site.

                Your correspondence or dealings with, or participation in promotions of, advertisers on the Site are solely between you and such advertisers. We will not be liable or responsible for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of advertisements on the Site.

                9. COOKIES
                A cookie is a small piece of text that is placed within the memory of a computer and can be later retrieved by web page servers. We use cookies to enhance your interaction and convenience with our Site.

                This Site may store cookies on your web browser in order to improve service for you on subsequent visits to the Site.

                By using cookies, web sites can track information about a visitor's use of the Site and provide customised content. Most web browsers can be configured to notify the user when a cookie is received, allowing you to either accept or reject it. You may also inspect the cookies stored by your web browser and remove any that you do not want.

                If you disable the use of cookies on your web browser or remove specific cookies from this Site or linked sites, then your use of the Site may be restricted.

                10. USE OF THE SITE IS AT YOUR RISK
                You use the Site at your own risk and everything on the Site is provided to you “as is” and “as available” without warranty or condition of any kind, either expressed or implied, including, but not limited to, any implied warranties of merchantability, fitness for a particular purpose, or non-infringement. If a jurisdiction does not allow the exclusion of implied warranties but allows limitations of a certain maximum extent then we limit our warranties to that extent.

                We exclude all representations and warranties to the fullest extent permissible under any Applicable Law

                11. LIMITATION OF LIABILITY
                To the extent permitted by law our aggregate liability to you is limited to the following, the choice of which is at our sole discretion:

                (a) In the case of goods:



                (i) the replacement of the goods or the supply of equivalent goods;
                (ii) the repair of the goods;
                (iii) the payment of the cost of replacing the goods or of acquiring equivalent goods; or
                (iv) the payment of the cost of having the goods repaired; or

                (b) in the case of services:



                (i) the supply of the services again; or
                (ii) the payment of the cost of having the services supplied again.

                To the extent permitted by law we will not be liable for any direct, incidental, consequential or indirect damages, loss or corruption of data, loss of profits, goodwill, bargain or opportunity or loss of anticipated savings resulting from your access to, or use of, or inability to use the Site and the Content, whether based on warranty, contract, tort, negligence or any other legal theory, and whether or not we know of the possibility of such damage.

                If a jurisdiction does not allow the exclusion or limitation of liability in accordance with this clause but allows a limitation of a certain maximum extent then our liability is limited to that extent.

                12. GENERAL PROVISIONS
                We may revise these terms and conditions from time to time by updating this posting. The revised terms will take effect when they are posted.

                If any part of these terms and conditions is held to be unenforceable, the unenforceable part must be given effect to the greatest extent possible and the remainder will remain in full force and effect.

                This Site and your use of this Site are governed by the laws of New South Wales, Australia. By using this Site, you irrevocably submit to the exclusive jurisdiction of the courts of New South Wales, Australia.
            </p>
        </div>
    </div>
</div>